import type { ReactElement, ReactNode } from "react";
import "./global.css";

export const metadata = {
  description: "Generated by create-nx-workspace",
  title: "Welcome to live-sync",
};

export const RootLayout = ({
  children,
}: {
  children: ReactNode;
}): ReactElement => {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
};
export default RootLayout;
