export const skillsConfig = {
  backend: [
    "Node.js",
    "Express.js",
    "Python",
    "REST APIs",
    "BullMQ",
    "gRPC (NestJS)",
    "MongoDB",
    "Redis",
    "SQL",
    "Prisma",
  ],
  cloud: ["Firebase", "Vercel", "AWS S3", "Docker"],
  frontend: [
    "React",
    "TypeScript",
    "JavaScript",
    "Redux Toolkit",
    "RTK Query",
    "Next.js",
    "HTML",
    "CSS",
    "Tailwind CSS",
    "Material UI",
    "shadcn/ui",
    "CodeMirror",
  ],
  mobile: ["React Native", "React Native Web", "Expo"],
  tools: [
    "Vite",
    "Webpack",
    "Nx",
    "pnpm",
    "Git",
    "Jira",
    "CircleCI",
    "Jest",
    "React Testing Library",
    "SEO",
    "Deep Linking",
    "i18n",
    "Accessibility (a11y)",
    "Real-time (WebSockets, Supabase)",
  ],
};
